"""The cast's 3D files (art/CAST_3D.md): the move library, the characters, the manifest and the retarget math.

The files are generated by ``art/cast3d/build_cast.mjs`` from the owner's Higgsfield jobs; these tests check what
the page relies on: every model is a valid binary glTF, the bipeds share the rig's bone names, every move the page
asks for is in the library, sizes stay within a phone's budget, and the retarget math (run with Node when it is
installed) maps a rest pose onto a rest pose, round-trips exactly and removes walking travel.
"""

from __future__ import annotations

import json
import shutil
import struct
import subprocess
from pathlib import Path
from typing import Any

import pytest

ASSETS = Path(__file__).resolve().parents[1] / "src" / "nightcrawler" / "office_assets"
MANIFEST = ASSETS / "cast_manifest.json"
BIPED_BONES = {
    "Hips", "Spine", "Spine01", "Spine02", "neck", "Head",
    "LeftShoulder", "LeftArm", "LeftForeArm", "LeftHand", "RightShoulder", "RightArm", "RightForeArm", "RightHand",
    "LeftUpLeg", "LeftLeg", "LeftFoot", "LeftToeBase", "RightUpLeg", "RightLeg", "RightFoot", "RightToeBase",
}
#: The moves the world's acting uses (cast_motion.js plays them by these names).
REQUIRED_MOVES = {"idle", "talk", "chat", "listen", "nod", "sit", "sit_talk", "cheer", "worried", "shrug", "think",
                  "wave", "drink", "look", "scheme", "carry", "walk_casual", "walk_skip", "walk_quick",
                  "walk_penguin", "walk_heavy"}
CAST = {"voss": "biped", "pip": "biped", "nyx": "octopus", "rook": "biped", "mote": "blob", "jet": "biped"}
MAX_MODEL_BYTES = 2_500_000
MAX_TOTAL_BYTES = 14_000_000


def _glb_json(path: Path) -> dict[str, Any]:
    data = path.read_bytes()
    magic, version, length = struct.unpack_from("<4sII", data, 0)
    assert magic == b"glTF" and version == 2, f"{path.name} is not binary glTF 2.0"
    assert length == len(data), f"{path.name}: header length {length} != file size {len(data)}"
    chunk_len, chunk_type = struct.unpack_from("<I4s", data, 12)
    assert chunk_type == b"JSON"
    doc: dict[str, Any] = json.loads(data[20 : 20 + chunk_len])
    return doc


@pytest.fixture(scope="module")
def manifest() -> dict[str, Any]:
    doc: dict[str, Any] = json.loads(MANIFEST.read_text())
    return doc


def test_manifest_lists_the_whole_cast(manifest: dict[str, Any]) -> None:
    assert manifest["version"] == 1
    chars = manifest["characters"]
    for cid, kind in CAST.items():
        assert chars[cid]["kind"] == kind, cid
        assert (ASSETS / chars[cid]["file"]).is_file(), cid
    assert chars["motecart"]["kind"] == "prop"
    for cid, c in chars.items():
        if c["kind"] == "biped":
            assert c["walk"] in manifest["clips"], f"{cid}'s walk {c['walk']} is not in the library"
            assert c["hips_height"] > 0 and c["armature"] > 0


def test_every_move_the_page_uses_is_in_the_library(manifest: dict[str, Any]) -> None:
    clips = manifest["clips"]
    assert REQUIRED_MOVES <= set(clips), sorted(REQUIRED_MOVES - set(clips))
    for name, c in clips.items():
        assert c["seconds"] > 0, name
        if c["walk"]:
            assert c["loop"] and c["speed_hips_per_s"] > 0.1, f"{name}: a walk needs a ground speed to match its feet"
        else:
            assert c["speed_hips_per_s"] == 0 or name in {"nod", "think", "worried", "drink"}, name
    doc = _glb_json(ASSETS / manifest["library"]["file"])
    names = {a["name"] for a in doc.get("animations", [])}
    assert names == set(clips), "clips.glb and the manifest disagree"
    nodes = {n.get("name") for n in doc["nodes"]}
    assert BIPED_BONES <= nodes
    assert not doc.get("meshes"), "the move library carries no mesh"


def test_characters_are_valid_and_bipeds_share_the_rig(manifest: dict[str, Any]) -> None:
    for cid, c in manifest["characters"].items():
        doc = _glb_json(ASSETS / c["file"])
        assert doc.get("meshes"), cid
        assert not doc.get("animations"), f"{cid}: moves live in clips.glb, not in the character"
        if c["kind"] == "biped":
            (skin,) = doc["skins"]
            joints = {doc["nodes"][j]["name"] for j in skin["joints"]}
            assert BIPED_BONES <= joints, f"{cid} misses {sorted(BIPED_BONES - joints)}"
        else:
            assert not doc.get("skins"), cid
        # every texture is webp and every buffer compressed: the page sets the meshopt decoder
        assert "EXT_meshopt_compression" in doc.get("extensionsRequired", []), cid
        for img in doc.get("images", []):
            assert img.get("mimeType") == "image/webp", cid


def test_sizes_fit_a_phone(manifest: dict[str, Any]) -> None:
    files = [manifest["library"]["file"]] + [c["file"] for c in manifest["characters"].values()]
    total = 0
    for name in files:
        size = (ASSETS / name).stat().st_size
        assert size <= MAX_MODEL_BYTES, f"{name} is {size} bytes"
        total += size
    assert total <= MAX_TOTAL_BYTES


def test_heights_match_the_lineup(manifest: dict[str, Any]) -> None:
    chars = manifest["characters"]
    assert chars["rook"]["size_m"][1] > 1.6 * chars["pip"]["size_m"][1]  # the golem towers over the crew
    for cid in ("voss", "pip", "jet"):
        assert 0.85 <= chars[cid]["size_m"][1] <= 1.1, cid


_JS = r"""
import * as rig from %(rig)s;
const out = {};
const q = (x, y, z, a) => rig.qaxis(x, y, z, a);
const src = { bones: {} }, dst = { bones: {} };
let parent = null;
for (const [i, b] of rig.BIPED_BONES.entries()) {
  src.bones[b] = { parent: b === "Hips" ? null : (b.includes("Shoulder") ? "Spine02" : b.includes("UpLeg") ? "Hips" : parent),
                   t: b === "Hips" ? [0, 40, 0] : [0, 5 + i * 0.1, 0], r: q(1, 0.2 * i, 0.1, 0.05 * i) };
  dst.bones[b] = { parent: src.bones[b].parent, t: b === "Hips" ? [0, 80, 0] : [0, 9, 0], r: q(0.3, 1, 0.2 * i, 0.11 * i) };
  parent = b.startsWith("Right") || b.startsWith("Left") ? (b.endsWith("Hand") || b.endsWith("ToeBase") ? "Spine02" : b) : b;
}
// a move: the rest pose with a twist on every bone over three frames and the hips travelling 30 units forward
const times = [0, 0.5, 1], move = { times, rot: {}, hips: [] };
for (const b of rig.BIPED_BONES) {
  const r = src.bones[b].r, arr = [];
  for (const k of [0, 1, 2]) arr.push(...rig.qnorm(rig.qmul(r, q(0, 1, 0, 0.2 * k))));
  move.rot[b] = arr;
}
for (const k of [0, 1, 2]) move.hips.push(0, 40 + k, 15 * k);
const restMove = { times: [0], rot: Object.fromEntries(rig.BIPED_BONES.map((b) => [b, src.bones[b].r])), hips: [0, 40, 0] };
const atRest = rig.retarget(src, dst, restMove);
out.restErr = Math.max(...rig.BIPED_BONES.map((b) => 1 - Math.abs(rig.qdot(atRest.rot[b].slice(0, 4), dst.bones[b].r))));
const there = rig.retarget(src, dst, move, { keepTravel: true });
const back = rig.retarget(dst, src, there, { keepTravel: true });
out.roundErr = Math.max(...rig.BIPED_BONES.flatMap((b) => [0, 1, 2].map((f) => 1 - Math.abs(rig.qdot(back.rot[b].slice(4 * f, 4 * f + 4), move.rot[b].slice(4 * f, 4 * f + 4))))));
out.hipsBack = back.hips;
const stripped = rig.retarget(src, dst, move, {});
out.strippedZ = [stripped.hips[2], stripped.hips[5], stripped.hips[8]];
out.bobY = [stripped.hips[1], stripped.hips[4], stripped.hips[7]];
out.travel = rig.travelSpeed(move);
console.log(JSON.stringify(out));
"""


@pytest.mark.skipif(shutil.which("node") is None, reason="Node is not installed")
def test_retarget_math(tmp_path: Path) -> None:
    script = tmp_path / "t.mjs"
    script.write_text(_JS % {"rig": json.dumps((ASSETS / "cast_rig.js").as_uri())})
    res = subprocess.run(["node", str(script)], capture_output=True, text=True, timeout=60, check=True)
    out = json.loads(res.stdout)
    assert out["restErr"] < 1e-9, "the source rest pose must land exactly on the target rest pose"
    assert out["roundErr"] < 1e-9, "source -> target -> source must give the move back"
    assert out["hipsBack"] == pytest.approx([0, 40, 0, 0, 41, 15, 0, 42, 30], abs=1e-6)
    assert out["strippedZ"] == pytest.approx([0, 0, 0], abs=1e-9), "walking travel is removed (the page moves them)"
    assert out["bobY"] == pytest.approx([80, 82, 84], abs=1e-9), "the hips' bob scales with the hip height"
    assert out["travel"] == pytest.approx(30.0)


@pytest.mark.skipif(shutil.which("node") is None, reason="Node is not installed")
def test_motion_module_parses() -> None:
    # cast_motion.js imports "three" (an import map resolves it on the page); a syntax check is enough here
    res = subprocess.run(["node", "--check", str(ASSETS / "cast_motion.js")], capture_output=True, text=True, timeout=60, check=False)
    assert res.returncode == 0, res.stderr
